In [57]:
#Imports
import pandas as pd

In [60]:
# Mount the google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [61]:
# Import raw data for Indicators of Heart Disease, just in case the other dataset because of NANs cannot be taken up.
# Source of data = https://www.kaggle.com/datasets/kamilpytlak/personal-key-indicators-of-heart-disease
df = pd.read_csv('/content/drive/MyDrive/heart_2022_with_nans.csv')

In [62]:
# CLEAN DATA
# drop any NAN value rows from data
df.dropna(axis = 0, inplace = True)
df = df.reset_index(drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      246022 non-null  object
 1   Sex                        246022 non-null  object
 2   GeneralHealth              246022 non-null  object
 3   PhysicalHealthDays         246022 non-null  float64
 4   MentalHealthDays           246022 non-null  float64
 5   LastCheckupTime            246022 non-null  object
 6   PhysicalActivities         246022 non-null  object
 7   SleepHours                 246022 non-null  float64
 8   RemovedTeeth               246022 non-null  object
 9   HadHeartAttack             246022 non-null  object
 10  HadAngina                  246022 non-null  object
 11  HadStroke                  246022 non-null  object
 12  HadAsthma                  246022 non-null  object
 13  HadSkinCancer              246022 non-null  object
 14  HadCOPD                    246022 non-null  object
 15  HadDepressiveDisorder      246022 non-null  object
 16  HadKidneyDisease           246022 non-null  object
 17  HadArthritis               246022 non-null  object
 18  HadDiabetes                246022 non-null  object
 19  DeafOrHardOfHearing        246022 non-null  object
 20  BlindOrVisionDifficulty    246022 non-null  object
 21  DifficultyConcentrating    246022 non-null  object
 22  DifficultyWalking          246022 non-null  object
 23  DifficultyDressingBathing  246022 non-null  object
 24  DifficultyErrands          246022 non-null  object
 25  SmokerStatus               246022 non-null  object
 26  ECigaretteUsage            246022 non-null  object
 27  ChestScan                  246022 non-null  object
 28  RaceEthnicityCategory      246022 non-null  object
 29  AgeCategory                246022 non-null  object
 30  HeightInMeters             246022 non-null  float64
 31  WeightInKilograms          246022 non-null  float64
 32  BMI                        246022 non-null  float64
 33  AlcoholDrinkers            246022 non-null  object
 34  HIVTesting                 246022 non-null  object
 35  FluVaxLast12               246022 non-null  object
 36  PneumoVaxEver              246022 non-null  object
 37  TetanusLast10Tdap          246022 non-null  object
 38  HighRiskLastYear           246022 non-null  object
 39  CovidPos                   246022 non-null  object
dtypes: float64(6), object(34)
memory usage: 75.1+ MB

In [63]:
# check for the count of non-NAN rows
df.count()

State                        246022
Sex                          246022
GeneralHealth                246022
PhysicalHealthDays           246022
MentalHealthDays             246022
LastCheckupTime              246022
PhysicalActivities           246022
SleepHours                   246022
RemovedTeeth                 246022
HadHeartAttack               246022
HadAngina                    246022
HadStroke                    246022
HadAsthma                    246022
HadSkinCancer                246022
HadCOPD                      246022
HadDepressiveDisorder        246022
HadKidneyDisease             246022
HadArthritis                 246022
HadDiabetes                  246022
DeafOrHardOfHearing          246022
BlindOrVisionDifficulty      246022
DifficultyConcentrating      246022
DifficultyWalking            246022
DifficultyDressingBathing    246022
DifficultyErrands            246022
SmokerStatus                 246022
ECigaretteUsage              246022
ChestScan                    246022
RaceEthnicityCategory        246022
AgeCategory                  246022
HeightInMeters               246022
WeightInKilograms            246022
BMI                          246022
AlcoholDrinkers              246022
HIVTesting                   246022
FluVaxLast12                 246022
PneumoVaxEver                246022
TetanusLast10Tdap            246022
HighRiskLastYear             246022
CovidPos                     246022
dtype: int64

In [64]:
pd.options.display.max_columns = None # to allow visibility of all columns when doing .head()
df.head(5)

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,BlindOrVisionDifficulty,DifficultyConcentrating,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,ChestScan,RaceEthnicityCategory,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 65 to 69,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,No,No,No,No,No,No,No,Yes,Yes,No,No,No,No,No,No,Former smoker,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 70 to 74,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,No,No,No,No,No,No,No,Yes,No,No,Yes,No,Yes,No,No,Former smoker,Never used e-cigarettes in my entire life,Yes,"White only, Non-Hispanic",Age 75 to 79,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,No,No,No,Yes,No,Yes,No,Yes,No,No,No,No,Yes,No,No,Never smoked,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 80 or older,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,No,Never smoked,Never used e-cigarettes in my entire life,No,"White only, Non-Hispanic",Age 80 or older,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [65]:
# Change some columns to 'string' datatype.
df[['State', 'Sex', 'GeneralHealth', 'LastCheckupTime', 'RemovedTeeth', 'SmokerStatus', 'ECigaretteUsage', 'RaceEthnicityCategory', 'AgeCategory', 'TetanusLast10Tdap']] = (
    df[['State', 'Sex', 'GeneralHealth', 'LastCheckupTime', 'RemovedTeeth', 'SmokerStatus', 'ECigaretteUsage', 'RaceEthnicityCategory', 'AgeCategory', 'TetanusLast10Tdap']].astype('string')
)

# change 'PhysicalHealthDays', 'MentalHealthDays' to int datatype as their values are basically integers
df[['PhysicalHealthDays', 'MentalHealthDays']] = (
    df[['PhysicalHealthDays', 'MentalHealthDays']].astype(int)
)

# change columns with boolean values (Yes, No) to (1,0)
# Define the mapping dictionary
mapping = {'Yes': 1, 'No': 0}
# Use the replace() method with the mapping dictionary
df.replace(mapping, inplace=True)

In [66]:
# checking again to see if all seemingly boolean columns have been converted to int datatypes or not?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      246022 non-null  string
 1   Sex                        246022 non-null  string
 2   GeneralHealth              246022 non-null  string
 3   PhysicalHealthDays         246022 non-null  int64
 4   MentalHealthDays           246022 non-null  int64
 5   LastCheckupTime            246022 non-null  string
 6   PhysicalActivities         246022 non-null  int64
 7   SleepHours                 246022 non-null  float64
 8   RemovedTeeth               246022 non-null  string
 9   HadHeartAttack             246022 non-null  int64
 10  HadAngina                  246022 non-null  int64
 11  HadStroke                  246022 non-null  int64
 12  HadAsthma                  246022 non-null  int64
 13  HadSkinCancer              246022 non-null  int64
 14  HadCOPD                    246022 non-null  int64
 15  HadDepressiveDisorder      246022 non-null  int64
 16  HadKidneyDisease           246022 non-null  int64
 17  HadArthritis               246022 non-null  int64
 18  HadDiabetes                246022 non-null  object
 19  DeafOrHardOfHearing        246022 non-null  int64
 20  BlindOrVisionDifficulty    246022 non-null  int64
 21  DifficultyConcentrating    246022 non-null  int64
 22  DifficultyWalking          246022 non-null  int64
 23  DifficultyDressingBathing  246022 non-null  int64
 24  DifficultyErrands          246022 non-null  int64
 25  SmokerStatus               246022 non-null  string
 26  ECigaretteUsage            246022 non-null  string
 27  ChestScan                  246022 non-null  int64
 28  RaceEthnicityCategory      246022 non-null  string
 29  AgeCategory                246022 non-null  string
 30  HeightInMeters             246022 non-null  float64
 31  WeightInKilograms          246022 non-null  float64
 32  BMI                        246022 non-null  float64
 33  AlcoholDrinkers            246022 non-null  int64
 34  HIVTesting                 246022 non-null  int64
 35  FluVaxLast12               246022 non-null  int64
 36  PneumoVaxEver              246022 non-null  int64
 37  TetanusLast10Tdap          246022 non-null  string
 38  HighRiskLastYear           246022 non-null  int64
 39  CovidPos                   246022 non-null  object
dtypes: float64(4), int64(24), object(2), string(10)
memory usage: 75.1+ MB

In [67]:
# Data exploration
# checking why 'HadDiabetes' and 'CovidPos'columns are still 'object' datatype?
unique_values_HadDiabetes = df['HadDiabetes'].unique()
unique_values_CovidPos = df['CovidPos'].unique()
print('unique_values_HadDiabetes: ', unique_values_HadDiabetes)
print('unique_values_unique_values_CovidPos: ', unique_values_CovidPos)

unique_values_HadDiabetes:  [0 1 'Yes, but only during pregnancy (female)'
 'No, pre-diabetes or borderline diabetes']
unique_values_unique_values_CovidPos:  [0 1 'Tested positive using home test without a health professional']

In [68]:
# Removing rows with HadDiabetes = 'Yes, but only during pregnancy (female)','No, pre-diabetes or borderline diabetes'
# Removing rows with CovidPos = 'Tested positive using home test without a health professional' considering it was not through a professional testing.
df = (df[(df['HadDiabetes'] != 'Yes, but only during pregnancy (female)')
& (df['HadDiabetes'] != 'No, pre-diabetes or borderline diabetes')
& (df['CovidPos'] != 'Tested positive using home test without a health professional')])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 230518 entries, 0 to 246021
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      230518 non-null  string
 1   Sex                        230518 non-null  string
 2   GeneralHealth              230518 non-null  string
 3   PhysicalHealthDays         230518 non-null  int64
 4   MentalHealthDays           230518 non-null  int64
 5   LastCheckupTime            230518 non-null  string
 6   PhysicalActivities         230518 non-null  int64
 7   SleepHours                 230518 non-null  float64
 8   RemovedTeeth               230518 non-null  string
 9   HadHeartAttack             230518 non-null  int64
 10  HadAngina                  230518 non-null  int64
 11  HadStroke                  230518 non-null  int64
 12  HadAsthma                  230518 non-null  int64
 13  HadSkinCancer              230518 non-null  int64
 14  HadCOPD                    230518 non-null  int64
 15  HadDepressiveDisorder      230518 non-null  int64
 16  HadKidneyDisease           230518 non-null  int64
 17  HadArthritis               230518 non-null  int64
 18  HadDiabetes                230518 non-null  object
 19  DeafOrHardOfHearing        230518 non-null  int64
 20  BlindOrVisionDifficulty    230518 non-null  int64
 21  DifficultyConcentrating    230518 non-null  int64
 22  DifficultyWalking          230518 non-null  int64
 23  DifficultyDressingBathing  230518 non-null  int64
 24  DifficultyErrands          230518 non-null  int64
 25  SmokerStatus               230518 non-null  string
 26  ECigaretteUsage            230518 non-null  string
 27  ChestScan                  230518 non-null  int64
 28  RaceEthnicityCategory      230518 non-null  string
 29  AgeCategory                230518 non-null  string
 30  HeightInMeters             230518 non-null  float64
 31  WeightInKilograms          230518 non-null  float64
 32  BMI                        230518 non-null  float64
 33  AlcoholDrinkers            230518 non-null  int64
 34  HIVTesting                 230518 non-null  int64
 35  FluVaxLast12               230518 non-null  int64
 36  PneumoVaxEver              230518 non-null  int64
 37  TetanusLast10Tdap          230518 non-null  string
 38  HighRiskLastYear           230518 non-null  int64
 39  CovidPos                   230518 non-null  object
dtypes: float64(4), int64(24), object(2), string(10)
memory usage: 72.1+ MB

In [69]:
# Now changing the two remaining columns to int datatypes
df[['HadDiabetes', 'CovidPos']] = (
    df[['HadDiabetes', 'CovidPos']].astype(int)
)

In [70]:
df.head(5)

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadSkinCancer,HadCOPD,HadDepressiveDisorder,HadKidneyDisease,HadArthritis,HadDiabetes,DeafOrHardOfHearing,BlindOrVisionDifficulty,DifficultyConcentrating,DifficultyWalking,DifficultyDressingBathing,DifficultyErrands,SmokerStatus,ECigaretteUsage,ChestScan,RaceEthnicityCategory,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4,0,Within past year (anytime less than 12 months ...,1,9.0,None of them,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,Former smoker,Never used e-cigarettes in my entire life,0,"White only, Non-Hispanic",Age 65 to 69,1.60,71.67,27.99,0,0,1,1,"Yes, received Tdap",0,0
1,Alabama,Male,Very good,0,0,Within past year (anytime less than 12 months ...,1,6.0,None of them,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,Former smoker,Never used e-cigarettes in my entire life,0,"White only, Non-Hispanic",Age 70 to 74,1.78,95.25,30.13,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0
2,Alabama,Male,Very good,0,0,Within past year (anytime less than 12 months ...,0,8.0,"6 or more, but not all",0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,Former smoker,Never used e-cigarettes in my entire life,1,"White only, Non-Hispanic",Age 75 to 79,1.85,108.86,31.66,1,0,0,1,"No, did not receive any tetanus shot in the pa...",0,1
3,Alabama,Female,Fair,5,0,Within past year (anytime less than 12 months ...,1,9.0,None of them,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,Never smoked,Never used e-cigarettes in my entire life,0,"White only, Non-Hispanic",Age 80 or older,1.70,90.72,31.32,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,1
4,Alabama,Female,Good,3,15,Within past year (anytime less than 12 months ...,1,5.0,1 to 5,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,Never smoked,Never used e-cigarettes in my entire life,0,"White only, Non-Hispanic",Age 80 or older,1.55,79.38,33.07,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,0

In [75]:
# Data exploration to see all the category column values
unique_values_GeneralHealth = df['GeneralHealth'].unique()
unique_values_LastCheckupTime = df['LastCheckupTime'].unique()
unique_values_RemovedTeeth = df['RemovedTeeth'].unique()
unique_values_SmokerStatus = df['SmokerStatus'].unique()
unique_values_ECigaretteUsage = df['ECigaretteUsage'].unique()
unique_values_RaceEthnicityCategory = df['RaceEthnicityCategory'].unique()
unique_values_AgeCategory = df['AgeCategory'].unique()
unique_values_TetanusLast10Tdap = df['TetanusLast10Tdap'].unique()
print('unique values in \'GeneralHealth\': ', unique_values_GeneralHealth)
print('\n','unique values in \'LastCheckupTime\': ', unique_values_LastCheckupTime)
print('\n','unique values in \'RemovedTeeth\': ', unique_values_RemovedTeeth)
print('\n','unique values in \'SmokerStatus\': ', unique_values_SmokerStatus)
print('\n','unique values in \'ECigaretteUsage\': ', unique_values_ECigaretteUsage)
print('\n','unique values in \'RaceEthnicityCategory\': ', unique_values_RaceEthnicityCategory)
print('\n','unique values in \'AgeCategory\': ', unique_values_AgeCategory)
print('\n','unique values in \'TetanusLast10Tdap\': ', unique_values_TetanusLast10Tdap)

unique values in 'GeneralHealth':  <StringArray>
['Very good', 'Fair', 'Good', 'Excellent', 'Poor']
Length: 5, dtype: string

 unique values in 'LastCheckupTime':  <StringArray>
[     'Within past year (anytime less than 12 months ago)',
                                     '5 or more years ago',
  'Within past 2 years (1 year but less than 2 years ago)',
 'Within past 5 years (2 years but less than 5 years ago)']
Length: 4, dtype: string

 unique values in 'RemovedTeeth':  <StringArray>
['None of them', '6 or more, but not all', '1 to 5', 'All']
Length: 4, dtype: string

 unique values in 'SmokerStatus':  <StringArray>
[                        'Former smoker',
                          'Never smoked',
 'Current smoker - now smokes every day',
 'Current smoker - now smokes some days']
Length: 4, dtype: string

 unique values in 'ECigaretteUsage':  <StringArray>
['Never used e-cigarettes in my entire life',
                        'Use them some days',
                    'Not at all (right now)',
                        'Use them every day']
Length: 4, dtype: string

 unique values in 'RaceEthnicityCategory':  <StringArray>
[     'White only, Non-Hispanic',      'Black only, Non-Hispanic',
 'Other race only, Non-Hispanic',     'Multiracial, Non-Hispanic',
                      'Hispanic']
Length: 5, dtype: string

 unique values in 'AgeCategory':  <StringArray>
[   'Age 65 to 69',    'Age 70 to 74',    'Age 75 to 79', 'Age 80 or older',
    'Age 50 to 54',    'Age 40 to 44',    'Age 60 to 64',    'Age 55 to 59',
    'Age 45 to 49',    'Age 35 to 39',    'Age 25 to 29',    'Age 30 to 34',
    'Age 18 to 24']
Length: 13, dtype: string

 unique values in 'TetanusLast10Tdap':  <StringArray>
[                                       'Yes, received Tdap',
         'Yes, received tetanus shot but not sure what type',
 'No, did not receive any tetanus shot in the past 10 years',
                  'Yes, received tetanus shot, but not Tdap']
Length: 4, dtype: string